BEGIN TRY

BEGIN TRAN;

-- CreateTable
CREATE TABLE [dbo].[CLAVES_RUTAS] (
    [ClavesRutaId] NVARCHAR(1000) NOT NULL,
    [CLAVE_CATASTRAL] NVARCHAR(255) NOT NULL,
    [RUTA] NVARCHAR(255) NOT NULL,
    [UMAPS] FLOAT(53) NOT NULL,
    CONSTRAINT [CLAVES_RUTAS_pkey] PRIMARY KEY CLUSTERED ([ClavesRutaId]),
    CONSTRAINT [CLAVES_RUTAS_CLAVE_CATASTRAL_key] UNIQUE NONCLUSTERED ([CLAVE_CATASTRAL])
);

-- CreateTable
CREATE TABLE [dbo].[MORA] (
    [MoraId] NVARCHAR(1000) NOT NULL,
    [ART_ID_DOC] NVARCHAR(255) NOT NULL,
    [ACT_ID_CARD] NVARCHAR(40) NOT NULL,
    [NOMBRE] NVARCHAR(323) NOT NULL,
    [SECTOR_COLONIA] NVARCHAR(50) NOT NULL,
    [NOMBRE_COLONIA] NVARCHAR(60) NOT NULL,
    [OBL_YEAR] VARCHAR(50) NOT NULL,
    [DIAS] INT NOT NULL,
    [IMPUESTO] DECIMAL(38,2) NOT NULL,
    [TREN_DE_ASEO] DECIMAL(38,2) NOT NULL,
    [TASA_BOMBEROS] DECIMAL(38,2) NOT NULL,
    CONSTRAINT [MORA_pkey] PRIMARY KEY CLUSTERED ([MoraId])
);

-- CreateTable
CREATE TABLE [dbo].[RUTAS_COLONIA] (
    [RutaColoniaId] NVARCHAR(1000) NOT NULL,
    [RUTA] NVARCHAR(255) NOT NULL,
    [COLONIA] NVARCHAR(255) NOT NULL,
    CONSTRAINT [RUTAS_COLONIA_pkey] PRIMARY KEY CLUSTERED ([RutaColoniaId]),
    CONSTRAINT [RUTAS_COLONIA_RUTA_key] UNIQUE NONCLUSTERED ([RUTA])
);

-- AddForeignKey
ALTER TABLE [dbo].[CLAVES_RUTAS] ADD CONSTRAINT [CLAVES_RUTAS_RUTA_fkey] FOREIGN KEY ([RUTA]) REFERENCES [dbo].[RUTAS_COLONIA]([RUTA]) ON DELETE NO ACTION ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE [dbo].[MORA] ADD CONSTRAINT [MORA_ART_ID_DOC_fkey] FOREIGN KEY ([ART_ID_DOC]) REFERENCES [dbo].[CLAVES_RUTAS]([CLAVE_CATASTRAL]) ON DELETE NO ACTION ON UPDATE CASCADE;

COMMIT TRAN;

END TRY
BEGIN CATCH

IF @@TRANCOUNT > 0
BEGIN
    ROLLBACK TRAN;
END;
THROW

END CATCH
